MADMAC=$(JAGSDK)/tools/bin/rmac
ALN=$(JAGSDK)/tools/bin/rln

CC=$(JAGSDK)/tools/bin/m68k-aout-gcc
LIB=$(JAGSDK)/jaguar/rmvlib/lib
LIBGCC=$(JAGSDK)/tools/lib/gcc/m68k-aout/3.4.6/
INCL=$(JAGSDK)/jaguar/rmvlib/include

DFLAGS=-DINCLUDE_BENCHMARK
ALNFLAGS=-rq -v -v -v -w -y $(LIB)
MACFLAGS=-fb -v
CFLAGS=$(DFLAGS) -Wall -Werror -fomit-frame-pointer -O2 -msoft-float -funroll-loops -I$(INCL)
