MADMAC=$(JAGPATH)/bin/mac
ALN=$(JAGPATH)/bin/aln
WDB=$(JAGPATH)/bin/wdb
RDB=$(JAGPATH)/bin/rdbjag
LO=$(JAGPATH)/bin/lo -p $(PARIRQ)
JCP=$(JAGPATH)/bin/jcp
CONVERTER=$(JAGPATH)/bin/converter
OCAML=ocaml
LZ77=$(JAGPATH)/bin/lz77

CROSSPATH?=$(M68KTOOLS)/m68k-aout
CC=$(CROSSPATH)/bin/gcc
LIB=$(CROSSPATH)/lib/m68000
INCL=$(CROSSPATH)/include

CATNIPLO=$(JAGPATH)/bin/lo_catnip
CATNIPTTY?=/dev/ttyUSB0

DFLAGS=
ALNFLAGS=-rq -v -v -v -w -y $(LIB)
MACFLAGS=-fb -v
CFLAGS=$(DFLAGS) -m68000 -Wall -Werror -fomit-frame-pointer -O2 -msoft-float -funroll-loops $(INCL)
